"""Validation tests for DNN exported artifacts.

These tests verify that the model files generated by running
notebooks/dnn/02_export.ipynb and 03_strategy.ipynb are valid
and loadable. Skipped when artifacts are not present on disk.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

torch = pytest.importorskip("torch")

REPO_ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = REPO_ROOT / "models" / "dnn_v1.pt"
SCALER_PATH = REPO_ROOT / "models" / "dnn_scaler_v1.joblib"
FEATURE_COLS_PATH = REPO_ROOT / "models" / "dnn_feature_cols_v1.joblib"
FEATURES_JSON_PATH = REPO_ROOT / "data" / "optimal_features_dnn.json"
STRATEGY_JSON_PATH = REPO_ROOT / "data" / "optimal_strategy_dnn.json"

EXPECTED_RAW_COLS = [
    "btc_price",
    "elapsed_pct",
    "market_volume",
    "up_best_bid",
    "up_best_ask",
    "up_bid_depth",
    "up_ask_depth",
    "down_best_bid",
    "down_best_ask",
    "down_bid_depth",
    "down_ask_depth",
]

artifacts_exist = pytest.mark.skipif(
    not MODEL_PATH.exists(), reason="DNN artifacts not on disk (run 02_export.ipynb first)"
)
strategy_exists = pytest.mark.skipif(
    not STRATEGY_JSON_PATH.exists(), reason="Strategy config not on disk (run 03_strategy.ipynb first)"
)


@artifacts_exist
class TestModelArtifacts:
    def test_model_loads_and_produces_output(self):
        model = torch.load(MODEL_PATH, weights_only=False)
        model.eval()
        x = torch.randn(1, 11)
        with torch.no_grad():
            out = model(x)
        assert out.shape == (1, 1)

    def test_scaler_loads(self):
        import joblib

        scaler = joblib.load(SCALER_PATH)
        assert hasattr(scaler, "transform")
        assert hasattr(scaler, "mean_")

    def test_feature_cols_match_expected(self):
        import joblib

        cols = joblib.load(FEATURE_COLS_PATH)
        assert cols == EXPECTED_RAW_COLS
        assert len(cols) == 11

    def test_dnn_predictor_loads_artifacts(self):
        from polybot.adapters.dnn_predictor import DnnPredictor
        from polybot.ports.predictor import Predictor

        pred = DnnPredictor(
            model_path=str(MODEL_PATH),
            feature_cols_path=str(FEATURE_COLS_PATH),
            scaler_path=str(SCALER_PATH),
            temporal=False,
        )
        assert isinstance(pred, Predictor)

        row = {col: 1.0 for col in EXPECTED_RAW_COLS}
        p = pred.predict(row)
        assert 0.0 <= p <= 1.0


@artifacts_exist
class TestFeatureConfig:
    def test_features_json_has_required_fields(self):
        config = json.loads(FEATURES_JSON_PATH.read_text())
        assert config["model"] == "dnn_raw"
        assert config["n_features"] == 11
        assert config["features"] == EXPECTED_RAW_COLS
        assert config["architecture"] == "ResidualMLP"
        assert config["temporal"] is False

    def test_metrics_present(self):
        config = json.loads(FEATURES_JSON_PATH.read_text())
        metrics = config["metrics"]
        assert 0 < metrics["accuracy"] < 1
        assert 0 < metrics["brier"] < 1
        assert 0 < metrics["f1"] < 1


@strategy_exists
class TestStrategyConfig:
    def test_strategy_json_has_required_fields(self):
        config = json.loads(STRATEGY_JSON_PATH.read_text())
        assert config["model"] == "dnn"
        assert "min_edge" in config
        assert "max_entries" in config
        assert "walk_forward" in config["eval_method"]
        assert config["n_folds"] == 5

    def test_strategy_loadable_by_trading_strategy(self):
        from polybot.domain.trading_strategy import TradingStrategy

        ts = TradingStrategy.from_json(str(STRATEGY_JSON_PATH), name="DNN")
        assert ts.name == "DNN"
        assert ts.min_edge >= 0.0
        assert ts.max_entries >= 1
