"""Feedback learning system — structured observations, scorecard, and periodic reflection."""

from polybot.knowledge.constants import (
    BASE_KNOWLEDGE_FILES,
    CACHE_TTL_SECONDS,
    CHEAP_SIDE_THRESHOLD,
    DEFAULT_OBSERVATION_EXPIRY,
    DRAWDOWN_ALERT_THRESHOLD,
    EXPENSIVE_SIDE_THRESHOLD,
    FEATURE_CONFIG_FILENAME,
    LOSING_STREAK_THRESHOLD,
    MAX_NEW_OBSERVATIONS,
    MIN_EXPENSIVE_SIDE_TRADES,
    MIN_SIDE_SAMPLES,
    MIN_TRAILING_TRADES,
    OBSERVATIONS_FILENAME,
    PNL_THRESHOLD,
    RECENT_RESOLUTIONS_WINDOW,
    REFLECTION_MAX_TOKENS,
    REFLECTION_TEMPERATURE,
    SESSION_HISTORY_FILENAME,
    SESSION_HISTORY_MAX_ROWS,
    SIDE_ACCURACY_WARNING,
)
from polybot.knowledge.manager import REFLECTION_PROMPT, KnowledgeManager
from polybot.knowledge.scorecard import compute_scorecard, format_scorecard

__all__ = [
    # Manager
    "KnowledgeManager",
    "REFLECTION_PROMPT",
    # Scorecard
    "compute_scorecard",
    "format_scorecard",
    # Constants
    "PNL_THRESHOLD",
    "CACHE_TTL_SECONDS",
    "SESSION_HISTORY_MAX_ROWS",
    "REFLECTION_MAX_TOKENS",
    "REFLECTION_TEMPERATURE",
    "MAX_NEW_OBSERVATIONS",
    "DEFAULT_OBSERVATION_EXPIRY",
    "DRAWDOWN_ALERT_THRESHOLD",
    "RECENT_RESOLUTIONS_WINDOW",
    "EXPENSIVE_SIDE_THRESHOLD",
    "CHEAP_SIDE_THRESHOLD",
    "SIDE_ACCURACY_WARNING",
    "LOSING_STREAK_THRESHOLD",
    "MIN_TRAILING_TRADES",
    "MIN_SIDE_SAMPLES",
    "MIN_EXPENSIVE_SIDE_TRADES",
    "BASE_KNOWLEDGE_FILES",
    "OBSERVATIONS_FILENAME",
    "SESSION_HISTORY_FILENAME",
    "FEATURE_CONFIG_FILENAME",
]
